#!/bin/bash
pwd
echo "#####################"
ls -al
echo "#####################"
cd /app
#./proxy http -p :$PORT -t ws --local-ws-password pass
./proxy http -t wss -p "0.0.0.0:2096" --parent-ws-method="chacha20-ietf-poly1305" --parent-ws-password="srt1qaz"
#./proxy socks -t ws -p "0.0.0.0:8090" --parent-ws-method="chacha20-ietf-poly1305" --parent-ws-password="srt1qaz"
